name: Build Geocaching plugin
run-name: Build Geocaching plugin
on: [push]
jobs:
    Build-latest-jar:
        runs-on: ubuntu-latest
        steps:
            - name: Build | Prepare packages
              run: |
                    apt update; apt-get install software-properties-common -y
                    wget -O- https://apt.corretto.aws/corretto.key | apt-key add -
                    add-apt-repository 'deb https://apt.corretto.aws stable main'
                    apt-get update; apt-get install -y  maven java-21-amazon-corretto-jdk
            - name: Prepare | Setup git
              run: |
                    git config --global user.name "Radim Lipovčan"
                    git config --global user.email "radim@lipovcan.cz"
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Build | Gradle build
              run: |
                    ls -lah
                    chmod +x ./gradlew
                    ./gradlew build && ls -lah && ls */ -lah && ls */* -lah&& ls */*/* -lah
            - name: Build | publish jar
              run: |
                    curl --insecure --user username:mypass -T build/libs/EggHunt-1.0.jar ftp://192.168.10.133:/
            - name: Push | Create release
              uses: https://git.lipovcan.cz/Upstream/gitea-release-action.git@v1
              with:
                files: |-
                    build/libs/*.jar